#!/bin/bash

rm -f "$XDG_CONFIG_HOME/nnn/.lastd"
export NNN_PLUG="p:preview-tui"
export NNN_FIFO="$(mktemp -tu "$USER-XXXXXXXXXXXXXXXXXXX-nnn.fifo")"
export VISUAL="$EDITOR"
command nnn -P p -d -E -H $@
rm -f "$NNN_FIFO"
