#!/bin/bash
set -o noclobber -o noglob -o nounset

TABSIZE="  "

SHOULD_REBOOT=""

CONFIGPATH="$(dirname "$(realpath "$0")")"
echo "Path to config: $CONFIGPATH"

function setuser() {
	local TAB="$1"
	echo "$TAB[Setting up user $USER]"
	sudo usermod -aG audio $USER
}

function sethosts() {
	local TAB="$1"
	echo "$TAB[Setting up hosts file]"
	sudo cp "$CONFIGPATH/hosts" /etc/hosts
}

function symlink() {
	LSRC="$1"
	LDST="$2"
	local TAB="$3"
	echo "$TAB$LDST -> <config>/$LSRC"
	if [ -e "$LDST" ] && [ ! -L "$LDST" ]; then
		echo "$TAB$TABSIZE""creating backup $LDST -> $LDST.backup"
		sudo mv "$LDST" "$LDST.backup"
	fi
	rm -rf "$LDST"
	mkdir -p "$LDST"
	rm -rf "$LDST"
	LSRC="$CONFIGPATH/$LSRC"
	ln -sf "$LSRC" "$LDST"
}

function setlinks() {
	local TAB="$1"
	echo "$TAB[Creating symlinks]"
	mkdir -p "$HOME/.config"
	while read -r line; do
	    [[ "$line" == "#"* ]] && continue
		[[ "$line" == "" ]] && continue
		LDST=$(echo "$line" | awk -F'->' '{print $1}' | xargs)
		LSRC=$(echo "$line" | awk -F'->' '{print $2}' | xargs)
		LDST="$(eval echo "$LDST")"
		symlink "$LSRC" "$LDST" "$TAB$TABSIZE"
	done < "$CONFIGPATH/symlinks"
}

function setlocales() {
	local TAB="$1"
	echo "$TAB[Setting up locales]"
	if cmp -s "/etc/locale.gen" "$CONFIGPATH/locale.gen"; then
		echo "$TAB$TABSIZE""/etc/locale.gen is up to date"
	else
		echo "$TAB$TABSIZE""Copyng <config>/locale.gen -> /etc/locale.gen"
		sudo cp "$CONFIGPATH/locale.gen" "/etc/locale.gen"
		echo "$TAB$TABSIZE""Generate locales"
		sudo locale-gen
		SHOULD_REBOOT=true
	fi
	if cmp -s "/etc/locale.conf" "$CONFIGPATH/locale.conf"; then
		echo "$TAB$TABSIZE""/etc/locale.conf is up to date"
	else
		echo "$TAB$TABSIZE""Copyng <config>/locale.conf -> /etc/locale.conf"
		sudo cp "$CONFIGPATH/locale.conf" "/etc/locale.conf"
		SHOULD_REBOOT=true
	fi
}

function setx() {
	local TAB="$1"
	echo "$TAB[Setting up Xorg]"
	sudo mkdir -p /etc/X11/xorg.conf.d
	sudo chmod 755 /etc/X11 /etc/X11/xorg.conf.d
	while IFS= read -r file; do
		SOURCE="$CONFIGPATH/xorg/$file"
		DESTIN="/etc/X11/xorg.conf.d/10-$file"
		[ -d "$SOURCE" ] && continue
		echo "$TAB$TABSIZE cp <config>/xor/$file -> $DESTIN"
		sudo cp "$SOURCE" "$DESTIN"
	done <<< "$(ls "$CONFIGPATH/xorg")"
}

function setbash() {
	local TAB="$1"
	echo "$TAB[Setting up bash configs]"
	STARTXCMD='[[ $(tty) == /dev/tty1 ]] && exec startx'
	if grep -F -q "$STARTXCMD" ~/.bash_profile; then
		echo "$TAB$TABSIZE"".bash_profile already up to date"
	else
		echo "$TAB$TABSIZE""Adding startx >> .bash_profile"
		echo "$STARTXCMD" >> ~/.bash_profile
	fi
	LOADBRCCMD=". $CONFIGPATH/bashrc"
	if grep -F -q "$LOADBRCCMD" ~/.bashrc; then
		echo "$TAB$TABSIZE"".bashrc already up to date"
	else
		echo "$TAB$TABSIZE""Adding hook to .bashrc"
		echo "$LOADBRCCMD" >> ~/.bashrc
	fi
}

function setgpg() {
	local TAB="$1"
	echo "$TAB[Setting up GnuPG]"
	gpg --import "$CONFIGPATH/keys/"*
}

function installpkgs() {
	local TAB="$1"
	echo "$TAB[Installing packages]"
	sudo pacman -S --noconfirm --needed $(sed '/^[[:blank:]]*#/d;s/#.*//' $CONFIGPATH/pkgs | awk '{print $1}')
}

function installaur() {
	local TAB="$1"
	echo "$TAB[Installing aur stuff]"
	local place="$(pwd)"
	local installer="yay"
	if ! command -v "$installer" 2>&1 > /dev/null
	then
		echo "$TAB$TABSIZE""Need to install $installer"
		sudo pacman -S --noconfirm --needed --asdeps git base-devel
		local builddir="/tmp/build-setup-$installer-$USER"
		rm -rf "$builddir"
		mkdir -p "$builddir"
		cd "$builddir"
		git clone "https://aur.archlinux.org/$installer.git"
		cd "$installer"
		makepkg -si --needed --noconfirm
		yay --refresh --noconfirm
	fi
	cd "$place"
	yay -S --noconfirm --needed carapace-bin
	yay -S --noconfirm --needed cantata
	yay -S --noconfirm --needed sublime-text-4
	#yay -S --noconfirm --needed pwvucontrol
}

function setflatpak() {
	local TAB="$1"
	echo "$TAB[Setting up flatpak]"
	sudo mkdir -p /flatpak-aliases
	sudo chmod 755 /flatpak-aliases
	while IFS= read -r fltp; do
		read -r repo pkg als <<< "$fltp"
		sudo flatpak install -y "$repo" "$pkg"
		sudo flatpak override --device=all "$pkg"
		if [[ "$als" != "" ]]; then
			local FL_CMD="flatpak run $pkg "'$@'
			echo "$TAB$TABSIZE""Creagting alias script $als -> $FL_CMD"
			sudo rm -rf "/flatpak-aliases/$als"
			echo "$FL_CMD" | sudo tee -a "/flatpak-aliases/$als"
			sudo chmod 755 "/flatpak-aliases/$als"
		fi
	done <<< "$(sed '/^[[:blank:]]*#/d;s/#.*//' $CONFIGPATH/flatpak/installs)"
	#sudo flatpak update -y
}

function setpinas() {
	local TAB="$1"
	echo "$TAB[Sietting up PiNAS mount]"
	sudo mkdir -p /pinas2
	FSTAB_ENTRY="pinas2:/ /pinas2 nfs _netdev,noauto,vers=4.2,soft,retrans=10000,x-systemd.automount,x-systemd.mount-timeout=10,timeo=14,x-systemd.idle-timeout=1min 0 0"
	if grep -F -q "$FSTAB_ENTRY" /etc/fstab; then
		echo "$TAB$TABSIZE""fstab already up to date"
	else
		echo "$TAB$TABSIZE""Adding pinas2 entry to fstab"
		echo "$FSTAB_ENTRY" | sudo tee -a /etc/fstab
	fi
}

function setservices() {
	local TAB="$1"
	echo "$TAB[Enabling/disabling sysd services]"
	sudo systemctl daemon-reload
	sudo systemctl enable --now tailscaled
	sudo systemctl enable --now nix-daemon
	sudo systemctl enable --now bluetooth.service
	systemctl --user enable --now wireplumber.service
	systemctl --user enable --now pipewire-pulse.service
}

function setxdg() {
	local TAB="$1"
	echo "$TAB[Setting up XDG stuff]"
	while IFS= read -r mime; do
		echo "$TAB$TABSIZE""Setting up launcher as default app for $mime"
		xdg-mime default launcher.desktop "$mime"
	done <<< "$(cat "$CONFIGPATH/mimes")"
}

function setvscode() {
	local TAB="$1"
	echo "$TAB[Setting up vscode]"
	code --install-extension mikestead.dotenv
	code --install-extension aaron-bond.better-comments
	code --install-extension mkhl.direnv
	code --install-extension usernamehw.errorlens
	code --install-extension ms-vscode.hexeditor
	code --install-extension shd101wyy.markdown-preview-enhanced
	code --install-extension dcasella.monokai-plusplus
	code --install-extension jnoortheen.nix-ide
	code --install-extension ms-ceintl.vscode-language-pack-ru
	code --install-extension wayou.vscode-todo-highlight
	code --install-extension ms-vscode.wasm-wasi-core
}

function cond_reboot() {
	[[ $SHOULD_REBOOT != true ]] && return
	echo "!! There are some changes that requre reboot !!"
}

setuser ""
sethosts ""
setlocales ""
setlinks ""
setx ""
setbash ""
installpkgs ""
installaur ""
sudo pkgfile -u
setgpg ""
setflatpak ""
setxdg ""
setvscode ""
setpinas ""
setservices ""
# TODO: setup sudoers
# TODO: fix files permissions

cond_reboot
